apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-web-front-paulgiraldo
  labels:
    app: mi-web-front-paulgiraldo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-web-front-paulgiraldo
  template:
    metadata:
      labels:
        app: mi-web-front-paulgiraldo
    spec:
      containers:
        - name: mi-web-front-paulgiraldo
          image: paulgiraldo/frontend-react-k8:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mi-web-front-service-paulgiraldo
spec:
  selector:
    app: mi-web-front-paulgiraldo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer